export const FilterJobCategories = {
  Category: [
    "Web Developer",
    "UI/UX",
    "Frontend Developer",
    "Backend Developer",
    "React Developer",
    "Data Scientist",
    "Data Analytics",
    "AI/ML Developer",
    "Devops",
  ],
  "Job Type": ["Work from Office", "Work from Home", "Hybrid"],
  Location: [
    "Indore",
    "Pune",
    "Mumbai",
    "New Delhi",
    "Noida",
    "Gurgaon",
    "Bangalore",
    "Hyderabad",
  ],
};
export const FilterInternshipCategories = {
  Category: [
    "Web Developer",
    "UI/UX",
    "Frontend Developer",
    "Backend Developer",
    "React Developer",
    "Data Scientist",
    "Data Analytics",
    "AI/ML Developer",
    "Devops",
  ],
  "Job Type": [
    "Office Internship",
    "Virtual Internship",
    "Hybrid Internship",
    "Summer Internship",
  ],
  Compensation: ["Paid", "Unpaid"],
  Location: [
    "Indore",
    "Pune",
    "Mumbai",
    "New Delhi",
    "Noida",
    "Gurgaon",
    "Bangalore",
    "Hyderabad",
  ],
};
