export const MentorsDomain = [
  "How to Start",
  "College Exam Prep",
  "Placement Prep",
  "Web Development",
  "Frontend Developer",
  "App Development",
  "Frontend Developer",
  "DSA Guidance",
  "Aptitude Prep",
  "UI/UX",
  "Backend Developer",
  "Java Developer",
  "Full Stack Developer",
  "MERN Stack Developer",
  "Devops",
  "AI/ML",
  "Data Science",
  "Data Analytics",
];

export const Skills = [
  "DSA",
  "C",
  "Cpp",
  "Java",
  "Python",
  "HTML",
  "CSS",
  "Javascript",
  "React",
  "Angular",
  "Vue",
  "MongoDB",
  "NodeJS",
  "ExpressJS",
  "UI/UX",
  "Devops",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "Machine Learning",
  "Deep Learning",
  "Data Analytics",
  "Data Visualization",
  "Operating System",
  "Software Engineering",
  "MySQL",
  ".NET",
  "Oop",
  "GraphQL",
  "Oracle",
  "AWS",
  "Kuberantes",
  "Testing",
  "PHP",
  "SpringBoot",
  "Dart",
  "Blockchain",
];
